version: "2"

services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./volumes/proxy/certs:/etc/nginx/certs:ro"

  nginx-gen:
    restart: always
    build: ./samples/nginx-gen
    container_name: nginx-gen
    depends_on:
      - nginx
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    depends_on:
      - nginx
      - nginx-gen
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./volumes/proxy/certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

  sample-api:
    restart: always
    image: sample-api
    build: ./samples/api
    container_name: sample-api
    environment:
      - VIRTUAL_HOST=sushibarapi.ezoer.org
      - VIRTUAL_NETWORK=sushibar_default
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=sushibarapi.ezoer.org
      - LETSENCRYPT_EMAIL=ivan@learningequality.org

  sample-website:
    restart: always
    image: sample-website
    build: ./samples/website
    container_name: sample-website
    environment:
      - VIRTUAL_HOST=sushibar.ezoer.org
      - VIRTUAL_NETWORK=sushibar_default
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=sushibar.ezoer.org
      - LETSENCRYPT_EMAIL=ivan@learningequality.org

